# General Application configuration
spring:
  application:
    name: @project.name@
info:
  project-version: @project.version@
  build-timestamp: ${maven.build.timestamp}
controller:
  properties:
    base-path: /@project.name@/v1

# OpenAPI Definition
openapi:
  service:
    host: http://localhost:8080
    title: @project.name@
    version: @project.version@
    description: @project.description@
    contact:
      name: Raul Bolivar Navas
      email: rasysbox@hotmail.com

# Swagger Configuration
springdoc:
  api-docs:
    path: /@project.name@/v3/api-docs
  swagger-ui:
    path: /@project.name@/swagger-ui.html

